# Site settings
title: movement.futures
subtitle: Looking Forward
description: Workshop | 27-29 of January, 2017 | Vancouver
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://movementfutures.netlify.com"
location: Goldcorp Centre for the Arts
street_address: 149 West Hastings Street
city: Vancouver
state: BC
zip_code: V6B 1H4
country: Canada

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# Build settings
markdown: kramdown

sass:
  style: compressed
